# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: GALOP.WinMenu2Beletrik
PackageVersion: 2.0.2606.08
PackageLocale: cs-CZ
Publisher: GALOP, s.r.o.
PublisherUrl: https://www.galop.cz/
PublisherSupportUrl: https://www.galop.cz/kontakt
PrivacyUrl: https://www.galop.cz/wm2-privacy-policy.php
PackageName: WinMenu 2 Beletrik
PackageUrl: https://www.galop.cz/winmenu
License: Proprietary
Copyright: Copyright © GALOP, s.r.o. 2026
ShortDescription: Plně ozvučený program pro vyhledávání, stahování a čtení titulů z digitálních knihoven pro zrakově postižené.
Description: WinMenu 2 Beletrik je plně ozvučený program pro nevidomé a slabozraké uživatele, určený pro pohodlnou práci s černotiskovými i digitálními texty. Program umožňuje jednoduše vyhledávat, stahovat a číst tituly z digitálních knihoven pro zrakově postižené, číst černotiskové texty pomocí skeneru a převádět digitální texty do souborů MP3.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
